files:
  - source: Mod/FixRussianString/media/lua/shared/Translate/_unUsedInGame/*.txt
    translation: /Mod/FixRussianString/media/lua/shared/Translate/%two_letters_code%/%file_name%_%two_letters_code%.%file_extension%
    type: properties
